### ISSUE TITLE
High CPU Usage even if unused

### ISSUE THREAD

**Issue by vctender** [lukasjapan/bt-speaker#10] opened 2017-07-15 08:10 UTC
Hi all,

I recognized an issue in a RPI3 using bt speaker to use the Pi as an audio transceiver. First of all, bt-speaker is working fine without problems. I do not use the builtin WLAN module to avoid the sound problems.

After some time, even if not used, the python-process of bt-speaker constantly causes high cpu usage (100% on one core). How can I help to investigate?

Regards,

**Comment by lukasjapan** [comment] 2017-07-15 14:38
Hmmm,
maybe a first step would try to find out if the load comes from inside the C library or python. 
Probably it comes from python if the load is also high when not playing audio.

Approaches I could think of are:
- Add debug logging in code
- Monitor the DBUS for abnormalities

Maybe its even GLib responding unnecessarily to something. 

Personally I never experienced (or noticed) that issue since I use the Pi exclusively for bluetooth in my project.

**Comment by gonzotek** [comment] 2017-07-15 19:29
I am experiencing this as well.  It seems to happen shortly after the first bluetooth disconnect after a boot; at least for me.  I'm running bt-speaker on a RPi 3 using an up-to-date retropie image (installed retropie 4.2, then updated setup script and retropie packages using retropie's updated).  Also using ethernet, wifi is disabled via /boot/config.txt; I am using the onboard bluetooth however.

**Comment by vctender** [comment] 2017-07-15 20:12
Restarting bt_speaker resolves the issue immediately. I can confirm that it happens after disconnecting. Nevertheless the service seems to work fine, even with high cpu usage.

**Comment by lukasjapan** [comment] 2017-07-15 23:36
I can confirm it now. The raw_audio method is being called in a loop even when no audio data is available.

Will definitely look into this and fix it tonight or tomorrow.

A simple sleep if no audio data available should be sufficient if I can't find a smoother solution.

**Comment by vctender** [comment] 2017-07-16 06:52
n1, will validate your changes soon. Thanks

**Comment by lukasjapan** [comment] 2017-07-16 14:46
Turns out that bluez does not tell to release the filedescriptor of the audio stream on disconnect and the GObject listener went crazy.

It should be fixed now.

**Closed by lukasjapan** 2017-07-16 14:46 UTC

**Comment by gonzotek** [comment] 2017-07-16 22:37
Confirmed fixed for me (retropie 4.2 base image, packages all up-to-date as of 2017-07-16).  Thanks!!  Working great :-)

**Comment by vctender** [comment] 2017-07-21 17:33
confirmed - Thanks!
